/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UasPbo;

/**
 *
 * @author Lenovo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buku = new javax.swing.JTextField();
        Skripsi = new javax.swing.JTextField();
        Peminjaman = new javax.swing.JTextField();
        Profil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buku.setBackground(new java.awt.Color(255, 204, 0));
        Buku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Buku.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buku.setText("BUKU");
        Buku.setBorder(null);
        Buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BukuMouseClicked(evt);
            }
        });
        getContentPane().add(Buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, 20));

        Skripsi.setBackground(new java.awt.Color(255, 204, 0));
        Skripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Skripsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Skripsi.setText("SKRIPSI");
        Skripsi.setBorder(null);
        Skripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SkripsiMouseClicked(evt);
            }
        });
        getContentPane().add(Skripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 370, 70, 20));

        Peminjaman.setBackground(new java.awt.Color(255, 204, 0));
        Peminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Peminjaman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Peminjaman.setText("PEMINJAMAN");
        Peminjaman.setBorder(null);
        Peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(Peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 110, -1));

        Profil.setBackground(new java.awt.Color(255, 204, 0));
        Profil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Profil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Profil.setText("PROFIL");
        Profil.setBorder(null);
        Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilMouseClicked(evt);
            }
        });
        getContentPane().add(Profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UasPbo/Travalizer - Desktop (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BukuMouseClicked
        DataBuku Dashboard = new DataBuku();
            Dashboard.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BukuMouseClicked

    private void SkripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SkripsiMouseClicked
         DataSkripsi Dashboard = new DataSkripsi();
            Dashboard.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_SkripsiMouseClicked

    private void PeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanMouseClicked
         DataPeminjaman Dashboard = new DataPeminjaman();
            Dashboard.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_PeminjamanMouseClicked

    private void ProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseClicked
        Profil Dashboard = new Profil();
            Dashboard.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_ProfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buku;
    private javax.swing.JTextField Peminjaman;
    private javax.swing.JTextField Profil;
    private javax.swing.JTextField Skripsi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
