/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UasPbo;
import Coding.Peminjaman;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Lenovo
 */
public class DataPeminjaman extends javax.swing.JFrame {

     ArrayList<Peminjaman> DataPeminjaman;
    private int id=0;
    /**
     * Creates new form DataBuku
     */
    public DataPeminjaman() {
    try{
        DataPeminjaman = new ArrayList<>();
        initComponents();
        tampil();
    } catch (Exception e) {
        Logger.getLogger(DataPeminjaman.class.getName()).log(Level.SEVERE,null,e);
    }
}
    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    private void resetField(){
    Pengguna.setText("");
    Nama.setText("");
    Semester.setText("");
    Jurusan.setText("");
    Angkatan.setText("");
    Jenis.setText("");
    Status.setText("");
    Pinjam.setText("");
    Kembali.setText("");
    }
    private void tampil() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("PerpusPU").createEntityManager();
        entityManager.getTransaction().begin();
        TypedQuery<Peminjaman> querySelectAll = entityManager.createNamedQuery("Peminjaman.findAll", Peminjaman.class);
        List<Peminjaman> results = querySelectAll.getResultList();
        
         DefaultTableModel model = (DefaultTableModel) Peminjaman.getModel();
        model.setRowCount(0);
        for (Peminjaman data : results) {
            Object[] baris = new Object[9];
            baris[0] = data.getIdPengguna();
            baris[1] = data.getNama();
            baris[2] = data.getSemester();
            baris[3] = data.getJurusan();
            baris[4] = data.getAngkatan();
            baris[5] = data.getJenis();
            baris[6] = data.getStatus();
            baris[7] = data.getTanggalPeminjaman();
            baris[8] = data.getTanggalPengembalian();
           
            model.addRow(baris);
        }
        entityManager.getTransaction().commit();
          entityManager.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pengguna = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Semester = new javax.swing.JTextField();
        Jurusan = new javax.swing.JTextField();
        Kembali = new javax.swing.JTextField();
        Angkatan = new javax.swing.JTextField();
        Pinjam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Peminjaman = new javax.swing.JTable();
        Simpan = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        Sort = new javax.swing.JComboBox<>();
        Cari = new javax.swing.JButton();
        Back = new javax.swing.JLabel();
        Jenis = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 132, 160, 30));
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 182, 180, 30));
        getContentPane().add(Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 30));
        getContentPane().add(Jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 30));
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 130, 30));
        getContentPane().add(Angkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 150, 30));
        getContentPane().add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 150, 30));

        Peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pengguna", "Nama", "Semester", "Jurusan", "Angkatan", "Jenis", "Status", "Tanggal Peminjaman", "Tanggal Pengembalian"
            }
        ));
        Peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Peminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 780, 190));

        Simpan.setBackground(new java.awt.Color(0, 153, 102));
        Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        Ubah.setBackground(new java.awt.Color(0, 153, 102));
        Ubah.setForeground(new java.awt.Color(255, 255, 255));
        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        getContentPane().add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        Hapus.setBackground(new java.awt.Color(0, 153, 102));
        Hapus.setForeground(new java.awt.Color(255, 255, 255));
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        Cetak.setBackground(new java.awt.Color(0, 153, 102));
        Cetak.setForeground(new java.awt.Color(255, 255, 255));
        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });
        getContentPane().add(Cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 20));
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 160, -1));

        Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Pengguna", "Nama", "Semester", "Jurusan", "Angkatan", "Jenis", "Status", "Tanggal Peminjaman", "Tanggal Pengembalian", " " }));
        getContentPane().add(Sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 120, -1));

        Cari.setBackground(new java.awt.Color(0, 153, 102));
        Cari.setForeground(new java.awt.Color(255, 255, 255));
        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 50, 20));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));
        getContentPane().add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 160, 30));
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UasPbo/Travalizer - Desktop (4).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpanActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CetakActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CariActionPerformed

    private void PeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
         Dashboard Back = new Dashboard();
            Back.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angkatan;
    private javax.swing.JLabel Back;
    private javax.swing.JButton Cari;
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Jenis;
    private javax.swing.JTextField Jurusan;
    private javax.swing.JTextField Kembali;
    private javax.swing.JTextField Nama;
    private javax.swing.JTable Peminjaman;
    private javax.swing.JTextField Pengguna;
    private javax.swing.JTextField Pinjam;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField Semester;
    private javax.swing.JButton Simpan;
    private javax.swing.JComboBox<String> Sort;
    private javax.swing.JTextField Status;
    private javax.swing.JButton Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
